[package]
name = "mim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
base16 = "0.2.1"
blake3 = "1.8.2"
clap = { version = "4.5.53", features = ["derive"] }
flate2 = { version = "1.1.5", features = ["zlib-rs"] }
lender = "0.4.2"
libc = { version = "0.2.177", features = ["use_std"] }
libz-rs-sys = "0.5.3"
path-tools = "0.1.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_cbor = "0.11"
serde_json = { version = "1.0.145", features = ["indexmap", "preserve_order"] }
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
parking_lot = "0.12.5"
bincode = { version = "2.0.1", features = ["derive"] }
memchr = "2.8.0"
num_cpus = "1.17.0"
ctrlc = "3.5.1"

needletail = { version = "0.6.3", optional = true }
paraseq = { version = "0.4.3", optional = true }

[profile.release]
debug = true

[features]
# For MimReader::{get_needletail_reader,get_needletail_iter}
needletail = ["dep:needletail"]
# For using MimReader as paraseq::ParallelReader.
paraseq = ["dep:paraseq"]

default = ["needletail", "paraseq"]

[[bin]]
name = "mim"
required-features = ["needletail"]
